### ISSUE TITLE
Connection refused frontend

### ISSUE THREAD

**Issue by LeonardoGastiaburu** [googlecodelabs/monolith-to-microservices#10]
Hello all,

I have one issue when try to configure the network into GCP. I don't know what's the problem when the frontend try to "listening" the port configurated. Maybe is a firewall problem?

Here my issue, hope you can understand.

Every 2.0s: curl http://35.231.62.121:8080                                                                                  cs-6000-devshell-vm-004529bb-90b0-468b-b36e-40f5e720493b: Wed Jul 29 18:10:29 2020

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 35.231.62.121 port 8080: Connection refused

Thanks

**Comment by verbanicm** [comment]
@LeonardoGastiaburu,

Can you provide some more details? Are you following a specific codelab? If not, what steps did you take to get this far?

**Comment by LeonardoGastiaburu** [comment]
> @LeonardoGastiaburu,
> 
> Can you provide some more details? Are you following a specific codelab? If not, what steps did you take to get this far?

Hi @verbanicm 

I'll try to follow the example in qwiklabs "Hosting a Web App on Google Cloud Using Compute Engine".
so, I'm stuck in the part of configure a network to allocate the web app ""fancystore"

Thanks in advance

**Comment by verbanicm** [comment]
@LeonardoGastiaburu,

I imagine this is a firewall issue or an issue with assigning the appropriate tags to the compute instances so those firewall rules are matched. I would suggest the following:

-  Check the steps around configuring the network to see if you may have missed a step with creating firewall rules
-  Check your compute instances to see if they have the appropriate tags

```
gcloud compute instances list --format="table(name,status,tags.list())"
```

-  Start over with a clean slate (new project or qwiklab) depending on your entry point
