### ISSUE TITLE
In step 8 wrong instance-zone is specified

### ISSUE THREAD

**Issue by micsuc** [googlecodelabs/monolith-to-microservices#15]
Hi,

in step 8. Update website this part:
gcloud compute instance-templates create fancy-fe-new \
    --source-instance=frontend \
    --source-instance-zone=us-central1-a

Should have us-central1-f instead of us-central1-a

**Comment by verbanicm** [comment]
I have reached out to the author of that codelab to see if they can make those updates. Thanks for your help!
