### ISSUE TITLE
Missing example source repository

### ISSUE THREAD

**Issue by favsto** [googlecodelabs/monolith-to-microservices#3]
Hello, t
his lab doesn't contain a step with the command to check out the repository with example source code. 
There is a screenshot with a git clone command but it is a non-existent link.

Thank you in advance.
Fausto

**Comment by verbanicm** [comment]
Can you be more specific on which image or clone command? The only git clone command is to clone this repository and I was able to clone to my local just now.

`git clone https://github.com/googlecodelabs/monolith-to-microservices`

**Comment by favsto** [comment]
Hello verbanicm. 
Maybe we're talking about two different objects. My request is about a Google Codelab, please follow this link: https://codelabs.developers.google.com/codelabs/cloud-webapp-hosting-gce/index.html#1
You won't see a clone command. The only `git clone` command I see is in the screenshot of the cloud shell in the step no.2 of the codelab.

Regards,
Fausto

**Comment by verbanicm** [comment]
Got it! Seems like our Codelab interface doesn't like the Run in Cloud Shell button. The lab should be updated with a link to run in cloud shell and the manual steps to clone the repository!

Thanks for catching this!
