### ISSUE TITLE
[cloud-monolith-to-microservices-gke]: Kindly Update The Codebase. 

### ISSUE THREAD

**Issue by nishantabanik** [googlecodelabs/monolith-to-microservices#35]
One request to Google Team, Kindly Update The Codebase. 
Both the Products & Orders pages are Not working..

**Comment by verbanicm** [comment]
@nishantabanik I updated the codebase and ran through the codelab. All seems to be working now. Please re-open if you continue to have issues and please add any errors.

Thanks!
