### ISSUE TITLE
Misleading text about HTTPS support 

### ISSUE THREAD

**Issue by jaqx0r** [googlecodelabs/monolith-to-microservices#6]
https://codelabs.developers.google.com/codelabs/cloud-webapp-hosting-gcs/index.html?index=..%2F..index#0

has the words "How to Add HTTPS support with a HTTPS LoadBalancer" but this content doesn't exist in this codelab.

**Comment by verbanicm** [comment]
Thanks for the input! We are going to remove that section from the content.
