### ISSUE TITLE
Tutorial links to malware installation site

### ISSUE THREAD

**Issue by jschuh** [googlecodelabs/monolith-to-microservices#71]
The [Host a Static Website in Google Cloud with Cloud Storage](https://codelabs.developers.google.com/codelabs/cloud-webapp-hosting-gcs) tutorial includes links to `cookingincloudhipster.com`. When I clicked on one of these links I was redirected to a site that attempted to socially engineer me into installing a malicious search hijacking extension.

After making another navigation attempt from the same profile and source IP, the site started serving me more innocuous domain selling pages. However, testing from different profiles and source IPs resulted in further attempts to socially engineer me into installing various types of malware.

I assume the original author of the tutorial no longers own the domain, and it was grabbed by malware distributors. Regardless, it needs to be scrubbed from the tutorial as it presents a serious threat.

**Comment by cassierecher** [comment]
The tutorial in question has been removed. Thanks again!
